<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>flex在线编译</title>
	<style type="text/css">
.flex_compile {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background-color:#ededed;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #dcdcdc;
	display:inline-block;
	color:#777777;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:7px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.flex_compile:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background-color:#dfdfdf;
}.flex_compile:active {
	position:relative;
	top:1px;
}


/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
	<style type="text/css">
      .CodeMirror {border-top: 1px solid black; border-bottom: 1px solid black;}
      .CodeMirror-activeline-background {background: #e8f2ff !important;}
    </style>
	<link rel="stylesheet" href="./editor/codemirror.css">
    <script src="./editor/codemirror.js"></script>
    <script src="./editor/xml/xml.js"></script>
    <script src="./editor/selection/active-line.js"></script>
     <script src="./editor/swfobject.js"></script>
    <script type="text/javascript">
    	function genFlash()
    	{
    		document.getElementById("result").src="WfFlexCompile?text="+editor.getValue();
			//var flashvars = {};
			//var params = {};
			//var attributes = {};
			//swfobject.embedSWF("WfFlexCompile?text="+editor.getValue(), "flash", "500", "300", "10.2.0", false, flashvars, params, attributes);
    	}
    </script>
</head>
<body>
	<div><a href="javascript:genFlash()" class="flex_compile">编译</a></div>
	<div style="width:100%;height:100%;">
		<textarea id="code" name="code">
<?xml version="1.0" encoding="UTF-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009" xmlns:mx="library://ns.adobe.com/flex/mx" xmlns:s="library://ns.adobe.com/flex/spark">
	<s:Button label="Click Me2" click="hello(event)"/> 
	<fx:Script>
		<![CDATA[ 
            import mx.events.FlexEvent; 
 			import mx.controls.Alert;
 			import flash.events.Event;
            protected function hello(e:Event):void 
            { 
               	Alert.show("helloWorld"); 
           	} 
        ]]>
        </fx:Script>	
</s:Application>
		</textarea>
	</div>
	<div style="width:100%;height: 100%">
		<iframe id="result" width="100%" height="100%" frameborder="1"></iframe>
	</div>
	<script>
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
  mode: "application/xml",
  styleActiveLine: true,
  lineNumbers: true,
  lineWrapping: true
});
</script>
<!-- 
		
         -->
</body>
</html>